[package]
name = "rpp-wallet-interface"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
serde = { version = "=1.0.225", features = ["derive"] }
thiserror.workspace = true
serde_bytes = "=0.11.14"

[dev-dependencies]
serde_json.workspace = true
