[package]
name = "rpp-identity-tree"
version = "0.0.13"
edition.workspace = true
rust-version = "1.79"
license = "MIT"

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
prover-backend-interface = { path = "../zk/backend-interface" }
